apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    k8s-app: prometheus-k8s
  name: kube-rbac-proxy
  namespace: openshift-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "apiVersion": "metrics.k8s.io/v1beta1"
        "namespace": "{{ .Value }}"
        "resource": "pods"
      "rewrites":
        "byQueryParameter":
          "name": "namespace"
type: Opaque
