apiVersion: v1
kind: Route
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  path: /api/v2
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Reencrypt
  to:
    kind: Service
    name: alertmanager-main
