apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
  - delete
