apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-user-workload
  name: alertmanager-kube-rbac-proxy-tenancy
  namespace: openshift-user-workload-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "apiGroup": "monitoring.coreos.com"
        "namespace": "{{ .Value }}"
        "resource": "prometheusrules"
      "rewrites":
        "byQueryParameter":
          "name": "namespace"
type: Opaque
